### ISSUE TITLE
C# http template returns JSON / XML instead of plain text

### ISSUE THREAD

**Issue by davidebbo** [Azure/azure-webjobs-sdk-templates#109]
Not sure if this was a deliberate change, but raising it in case. Previously, HttpTriggerCSharp was returning text. Now, when I run it from portal, the response has JSON, e.g.

    "Hello Azure"

What I don't like is that if you run copy the function your and run it from new tab, you get XML, e.g.

```xml
<string xmlns="http://schemas.microsoft.com/2003/10/Serialization/">
Please pass a name on the query string or in the request body
</string>
```

That feels pretty heavy for what's supposed to be the simplest template. That may be a runtime issue rather than template.

**Comment by davidebbo** [comment]
Also, it's inconsistent with the node http template, which returns plain text.

**Comment by mathewc** [comment]
+1 on making these consistent. Regarding the returned content type - for C# we pretty much return the response the user created w/o modifying it, so likely not a runtime issue.

**Comment by davidebbo** [comment]
@mathewc on the runtime side, maybe it's possible to tweak WebAPI to always default to JSON? It just sucks that simply pasting the URL into a browser gives you XML :(

**Comment by fabiocav** [comment]
The behavior change was probably introduced with the template update as it was changed from creating an instance of an `HttpResponseMessage` to use the `CreateResponse` method on the request. 
I do like the current behavior as it is correctly negotiating the content type, though.

Regarding the default, it is already JSON, but you're likely making the request using Chrome, and the browser is sending an accept header that includes application/xml and not application/json and since there is a registered formatter that knows how to satisfy that, it will be used.

If you try using Edge (which doesn't include application/xml), you should get a JSON response as there will be no formatter to satisfy the accept header media types and will fallback to JSON. 

I can change it so that it always use JSON in the template. But I don't think we should change the runtime as it is behaving correctly.
Thoughts?

**Comment by davidebbo** [comment]
Thanks, I guess that makes sense. I guess let's not worry about this now, as it's way below the beta bar.

**Comment by christopheranderson** [comment]
The current functionality is correct. We should honor the "Accept" header as-is.
