### ISSUE TITLE
Review C# templates to make use of async and $return 

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-templates#314]

**Comment by mathewc** [comment]
You mean $return?

**Comment by davidebbo** [comment]
Yes. Whenever you have that case fixed we can switch to that.

**Comment by lindydonna** [comment]
@mathewc Can you point me to the bug that you're fixing related to this, so I can subscribe to it?

**Comment by mathewc** [comment]
Currently assigned to @brettsam https://github.com/Azure/azure-webjobs-sdk-script/issues/741

**Comment by soninaren** [comment]
From #314, Dup or subset of this issue

The following templates can be simplified:

https://github.com/Azure/azure-webjobs-sdk-templates/blob/dev/Templates/SaaSFileTrigger-CSharp/run.csx
https://github.com/Azure/azure-webjobs-sdk-templates/blob/dev/Templates/SendGrid-CSharp/run.csx
E.g. Instead of

```CSHARP
public static void Run(string input, string name, out string output, TraceWriter log)
{
    log.Info($"C# SaaS trigger function processed file: " + name);

    output = input;
}
```
Use:

```CSHARP
public static string Run(string input, string name, TraceWriter log)
{
    log.Info($"C# SaaS trigger function processed file: " + name);
    return input;
}
```

**Comment by soninaren** [comment]
Fixed in here https://github.com/Azure/azure-webjobs-sdk-templates/pull/361
