### ISSUE TITLE
EventHubTrigger-Python - We are unable to reach your function app (Internal Server Error). Please try again later. 

### ISSUE THREAD

**Issue by mnbf9rca** [Azure/azure-webjobs-sdk-templates#376]
I created a new EventHubTrigger-Python and almost immediately got this error. I updated function.json as follows:
```
{
  "bindings": [
    {
      "name": "myEventHubMessage",
      "topicName": "evohome-data",
      "connection": "evohome",
      "accessRights": "Manage",
      "type": "serviceBusTrigger",
      "direction": "in",
      "subscriptionName": "preprocess-data"
    }
  ],
  "disabled": false
}
```
run.py is:
```
import os

# read the queue message and write to stdout
input = open(os.environ['myEventHubMessage']).read()
message = "Python script processed Event Hub message '{0}'".format(input)
print(message)
```
I have enabled python 3.4 in function app settings.

the full error is:
```
We are unable to reach your function app (Internal Server Error). Please try again later. 
Session Id: e3aa15f73f2440d78526794fd81b21d0
Timestamp: 2016-12-11T09:34:44.195Z
```

**Comment by paulbatum** [comment]
Considering how our python support works right now, I think this template is going to be problematic. We know for python we have performance problems when there are a large number of invocations because we are spinning up a new process each invocation, and event hubs is specifically designed for high throughput, small messages. 

Lets remove this template until python works well for this type of workload.

**Comment by mnbf9rca** [comment]
@paulbatum what is the formal status of python support (in general, not this specific template)? I've currently got a support case open as whenever I enable python 3 support, my function apps start crashing with 404+500 errors (even if there are only c# functions in them).

**Comment by paulbatum** [comment]
@mnbf9rca Python support is in preview and is "as-is". You should expect it to stay in preview in the short term (next few months at a minimum). If you are looking at using Azure Functions for a production workload I would recommend using JS, C# or F#.

**Comment by mnbf9rca** [comment]
I believe this is because the web app setting for python version is incompatible with function apps. Is that correct? When will that be fixed?

**Comment by paulbatum** [comment]
@mnbf9rca I am not sure yet if we will actually make these two settings compatible. The reason for that is because we're not sure if we want to make Azure Functions capable of supporting multiple different versions of a given language/runtime. It would increase the complexity of our test matrix very significantly. For example, we only support one version of Node.js today (6.5.0).
