### ISSUE TITLE
Batch blob trigger binding fails

### ISSUE THREAD

**Issue by simonbill** [Azure/azure-webjobs-sdk-templates#384]
Creating a default batch blob trigger in the azure portal with config:

`{
  "bindings": [
    {
      "name": "myBlob",
      "type": "blobTrigger",
      "direction": "in",
      "path": "ourcontainer/{name}",
      "connection": "ourstorage_STORAGE"
    }
  ],
  "disabled": false
}`

Fails to execute with error: 
Exception while executing function: Functions.BlobTriggerOurFunction. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'myBlob'. Microsoft.Azure.WebJobs.Host: Blob identifiers must be in the format 'container/blob'.

Using exactly the same config with a default c# blob trigger works fine.

Assuming this is a bug?

**Comment by paulbatum** [comment]
@soninaren can you take a quick look at this?

**Comment by soninaren** [comment]
Fixed in here https://github.com/Azure/azure-webjobs-sdk-templates/pull/385

**Comment by soninaren** [comment]
@simonbill have fixed the bug in the template 
have updated the template to print blob size instead of the blob content, the change will not be visible in portal right now, new code is present [here](https://github.com/Azure/azure-webjobs-sdk-templates/blob/dev/Templates/BlobTrigger-Batch/run.bat)
To fix the bug manually

- make sure the test section has right side of the develop tab has value in the format container/blob
![image](https://cloud.githubusercontent.com/assets/8119379/21534019/dedb18d0-cd15-11e6-83a8-41e4b05fcba8.png)
- Also the container name in the path setting for blob trigger should match the container name in the Test section of the develop tab
![image](https://cloud.githubusercontent.com/assets/8119379/21534036/1978c726-cd16-11e6-8ecb-8a98f9f1df96.png)

**Comment by DaveVoyles** [comment]
I'm not sure if this has been fixed.

When running my function in the Azure Portal, all is fine. 

When running my function locally, via _func host start_, all is fine.

When running my function locally via  _func run MyBlobTriggerJS_:

` Exception while executing function: Functions.MyBlobTriggerJS. Microsoft.Azure.WebJobs.Host: Exception binding parameter 'myBlob'. Microsoft.Azure.WebJobs.Host: Blob identifiers must be in the format 'container/blob'.`

```
function.json

{
  "disabled": false,
  "bindings": [
    {
      "name": "myBlob",
      "type": "blobTrigger",
      "direction": "in",
      "path": "samples-workitems/{name}",
      "connection": "functionsstorageacct_STORAGE"
    }
  ]
}

```

You can view the (small) code base at that point in time, [here.](https://github.com/DaveVoyles/Azure-func-test/commit/aaaafb670413aeb97b9cca6bc08ae0788b8505d2)

Not sure why it throws that issue **only** when using func run MyBlobTriggerJS though.

**Comment by DaveVoyles** [comment]
I think I see things more clearly now, [via the docs:](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local)

> You can also invoke a function directly by using func run <FunctionName> and provide input data for the function. This command is similar to running a function using the Test tab in the Azure portal.

Looks like I need to pass in the argument _samples-workitems/{name}_ when I use the _run_ command.

**Comment by pmosconi** [comment]
Hi,
can someone please help me with how to pass the argument on command line with func run?
The docs say that it has to be in the form:
   {
        "input": "<trigger_input>"
    }
but I have no clue about trigger_input for blob trigger bindings

My function.json is:
    {
        "disabled" : false,
        "bindings" : [{
            "name" : "myBlob",
            "type" : "blobTrigger",
            "direction" : "in",
            "path" : "mystorage/{name}.csv",
            "connection" : "mystorage_STORAGE"
        }]
    }

Thanks in advance
