### ISSUE TITLE
Add local.settings.json to .gitignore in VS Function App template

### ISSUE THREAD

**Issue by lindydonna** [Azure/azure-webjobs-sdk-templates#494]
- Use the same contents as the default .gitignore, but add local.settings.json
- This needs to be completed within the next week so that we meet our timeline.

**Comment by soninaren** [comment]
fixed in https://github.com/Azure/azure-webjobs-sdk-templates/pull/498

**Comment by lukecolbourn** [comment]
Why was local.settings.json added to .gitignore? I'm thinking local.settings would be shared by a team of developers to make the function work locally? We're just about to remove it from our .gitignore, but happy for someone to tell us we're wrong to do so! 👍

**Comment by soninaren** [comment]
The reason it was added to .gitignore here was prevent the customer from accidentally pushing it azure, since it is only applicable to local environment. 

Also sharing the local.settings.json among developers for local development could cause some issues. For e.g, If the same storage is used between developers for storage based triggers , like a queue trigger, the message could be consumed by another developer running the function on his machine, and so on.

**Comment by Melcow** [comment]
Everytime when I switch branches, I have to add local.settings.json to the project again. And the issues @soninaren mentions when local.settings.json is shared amongst developers.. they will possibly arise anyway. When ignoring this file, developers will find a way to share the local.settings.json anyway...

**Comment by soninaren** [comment]
The issue here addresses the default state of a new functions project created via Visual Studio. Developers can definitely remove it from .gitignore if they find it suits their needs. 

It is simple meant to avoid accidentally checking in local.settings.json onto azure and to provide an indication this is used only in local scenarios. This was also in response to some confusion on part of several customers trying to use local.settings.json in Azure environment.

**Comment by lukecolbourn** [comment]
Makes sense thank you @soninaren

**Comment by ericbrunner** [comment]
@soninaren Where should e.g. connection strings put to ? When local.settings.json is ignored and not commited to central git repo (e.g. in VSTS) then everytime you clone that repo locally the local.settings.json and containing connection string is gone. Not suitable for development!!!

**Comment by svjmandryk** [comment]
it's quite cumbersome to share these local settings among developers without version control. especially after some time passes and no one remembers what values are expected there
