### ISSUE TITLE
Blob trigger node.js - change path name from sample-workitems to myblob

### ISSUE THREAD

**Issue by nirmash** [Azure/azure-webjobs-sdk-templates#50]
not a huge priority but couple of issues with current name:
1. sample-workitems sounds more like a queue not a file folder 
 2. having a dash is illegal for table storage (even though it is ok for blob storage might as well make it consistent) 
3. new name will be similar to the name of the object in code

**Comment by mathewc** [comment]
Changing the name is fine, but not "myblob" since the path is a **container** for multiple blobs. Perhaps "my-container" or "sample-items" or something like that. Also, the casing/naming of queues/containers shouldn't be camel cased like the parameter name (which is that way because it's a code variable).

All these "sample" names came from my initial sample scripts in the repo, where I was scenario driven, and the scenario for queues/blobs was that JSON work items were added and the scripts processed them.

**Comment by christopheranderson** [comment]
This is being done in the PR above.

**Comment by soninaren** [comment]
this is merged
