### ISSUE TITLE
Azure function Python - No JSON object could be decoded

### ISSUE THREAD

**Issue by HavardAustefjord** [Azure/azure-webjobs-sdk-templates#543]
I have have a problem related to decoding of JSON object when running the default "Hello world from <name>" function which is set as template for the Python HTTP trigger example. Error msg is ValueError: No JSON object could be decoded and the reason is that it does not find anything in the environment variable. This is triggered from postreqdata = json.loads(open(os.environ['req']).read()) in the default template.

I have tried the same in the JavaScript template which works out of the box.

The function runs on Python 2.7.13 with extension &name=MyName to the https adress.

**Comment by lindydonna** [comment]
@ahmelsayed Could  you take a look?

**Comment by HavardAustefjord** [comment]
To be more presice: The environment variable 'req' contains path to a temp file where the input should be stored. The path is typically: D:\\local\\Temp\\Functions\\Binding\\3318398f-d439-4b4a-bbac-b90c503507b6\\req

The file exists during execution of the function, but it is empty when the python script is triggered by the http call. It works when triggering it from the Azure Portal framework (Run button).

**Comment by HavardAustefjord** [comment]
I managed to call it directly from Python with success:

import requests
URL = 'https://xxxx.azurewebsites.net/api/FunctionName?code=SomeCode'
payload = {
    'name': MyName'
}
session = requests.session()
r = requests.post(URL, data=payload)

**Comment by baizini** [comment]
I also have exactly the same issue, is there a solution?

**Comment by tspanos** [comment]
By default, the Python HTTP-Trigger function comes with only `POST `enabled. Additionally, the test method that is being used in the Azure Functions IDE is also defaulted to `POST`. When the function runs under test conditions (in the Azure Functions IDE) it receives the data (JSON in the test box) and parses it with `json.loads(open(os.environ['req']).read())`. It then proceeds to build the response and output the desired text successfully.

The problem in discussion above occurs when a `GET `request is made (likely from a browser by appending a query to the function URL). Since we are using `GET` there is no longer an JSON payload, so `json.loads(open(os.environ['req']).read())` is going to error out. (Remember that when making a request with POST we are submitting data (JSON) with the body of the request and when make a request with `GET` we are using queries)

To correct the problem, make sure to enable `GET` (`GET `is not enabled by default and needs the be enabled in the _Integrate_ menu) and update your code to use the variable containing the query content.

```
import os
import json

response = open(os.environ['res'], 'w')
response.write("hello world from "+ os.environ['REQ_QUERY_NAME'])
response.close()
```

Your function should now work when accessing it from a browser URL. To test it using the Azure Functions IDE, switch the test method to `GET` and add a query with the name `name` and in the `value` field the value you want returned. 

Your function will no longer work with `POST` requests. I believe it is our responsibility as users to implement the functionality to allow our endpoint to handle different types of requests as Microsoft doesn't seem to have any documentation or Python libraries to help with this.

I hope this helps.

**Comment by paulbatum** [comment]
Good answer, closing this

**Comment by Dubl** [comment]
hello, please forgive me if this isn't the right place to post, but I'm having the same issue- I had a project that was working fine last year but now am getting the same result as above. It's in the context of a httptrigger function in a logic app. It works fine in the test window of the portal, but when called from the logic app, returns a blank body (which shows (correctly) as json in the executed logic app history.). the query items come over fine. I am stuck.
