### ISSUE TITLE
HTTP C# template is too complicated

### ISSUE THREAD

**Issue by paulbatum** [Azure/azure-webjobs-sdk-templates#63]
I do not think the current code looks approachable. This template probably needs to be rewritten from scratch.

**Comment by davidebbo** [comment]
Agreed that it grew a little crazy. Part of the reason is that it was made more flexible to handle both query string and body. But maybe we should hit a rest and just make it a plain Hello World. What we should have is a separate repo that is full of **samples**, and the current template would be a good fit there.

BTW, the JS template is mostly the same.

**Comment by paulbatum** [comment]
The JS template looks ok to me, its nowhere near as complicated.

**Comment by davidebbo** [comment]
Yeah, it does the same thing, but the language makes it look quite a bit simpler.

**Comment by fabiocav** [comment]
@paulbatum , @davidebbo , please take a look at PR #83 and let me know what you think. I cleaned things up to make it clearer and more concise.

**Comment by davidebbo** [comment]
Yep, awesome. Added yet a further simplification.
